---
- hosts: kube_control_plane[0] # Target the first control plane node
  become: yes
  tasks:
    # - name: Create config directory for haproxy on node
    #   ansible.builtin.file:
    #     path: /usr/local/etc/haproxy
    #     state: directory
    #     mode: '0755'
    #     owner: root
    #     group: root
    # - name: Add haproxy config
    #   ansible.builtin.copy:
    #     src: ../../helm/kube_ha/etc/haproxy/haproxy.cfg
    #     dest: /usr/local/etc/haproxy/haproxy.cfg
    #     owner: root
    #     group: root
    #     mode: '0644'
    # - name: Add haproxy manifest
    #   ansible.builtin.copy:
    #     src: ../../helm/kube_ha/haproxy.yaml
    #     dest: /etc/kubernetes/manifests/haproxy.yaml
    #     owner: root
    #     group: root
    #     mode: '0644'

    # - name: Create config directory for keepalived on node
    #   ansible.builtin.file:
    #     path: /usr/local/etc/keepalived
    #     state: directory
    #     mode: '0755'
    #     owner: root
    #     group: root
    # - name: Add keepalived config
    #   ansible.builtin.copy:
    #     src: ../../helm/kube_ha/etc/keepalived/keepalived.conf
    #     dest: /usr/local/etc/keepalived/keepalived.conf
    #     owner: root
    #     group: root
    #     mode: '0644'
    # - name: Create a unique auth_string
    #   ansible.builtin.set_fact:
    #     auth_string: "{{ lookup('community.general.random_string', length=24, special=false) }}"
    # - name: Fix the auth string in keepalived.conf
    #     path: /usr/local/etc/keepalived/keepalived.conf
    #     regexp: "CHANGE_ME"
    #     replace: "{{ auth_string }}"
    #     backup: no
    # - name: Add keepalived check script
    #   ansible.builtin.copy:
    #     src: ../../helm/kube_ha/etc/keepalived/check_apiserver.sh
    #     dest: /usr/local/etc/keepalived/check_apiserver.sh
    #     owner: root
    #     group: root
    #     mode: '0755'
    # - name: Add keepalived manifest
    #   ansible.builtin.copy:
    #     src: ../../helm/kube_ha/keepalived.yaml
    #     dest: /etc/kubernetes/manifests/keepalived.yaml
    #     owner: root
    #     group: root
    #     mode: '0644'

    - name: Create an Empty file for Kubeadm configuring
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: no

    - name: Configure container runtime
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          runtimeRequestTimeout: "15m"
          cgroupDriver: "systemd"
          systemReserved:
            cpu: 100m
            memory: 350M
          kubeReserved:
            cpu: 100m
            memory: 50M
          enforceNodeAllocatable:
          - pods
          ---
          apiVersion: kubeadm.k8s.io/v1beta4
          kind: ClusterConfiguration
          kubernetesVersion: stable
          controlPlaneEndpoint: "api.iron.lcsas.net:6443" # change this (see below)
          networking:
            podSubnet: "10.64.0.0/16"

    - name: Initialize the cluster
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml >> cluster_initialized.log
      args:
        chdir: /home/{{ ansible_user }}
        creates: cluster_initialized.log

    - name: Create Kubernetes config directory for ansible_user user
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to home directory
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Install packages required for first control plane node
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no
      loop:
        - python3-kubernetes

    - name: Restart and enable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
        enabled: yes

- hosts: kube_control_plane[0] # Target the first control plane node
  become: no
  tasks:
    - name: TCP port 6443 (On Master) is able to connect
      wait_for: "host={{ groups['kube_control_plane'][0] }} port=6443 timeout=1"

    - name: Install Calico CNI plugin
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/tigera-operator.yaml

    # I don't really like doing this, but a little delay seems to be necessary
    - name: Pause for 15 seconds so Calico CNI is available
      ansible.builtin.pause:
        seconds: 15

    - name: Apply Calico custom resources
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '~/helm/calico/calico-custom-resources.yaml')  | from_yaml_all }}"

    - name: Grab config file to access k8s
      ansible.builtin.fetch:
        src: /home/{{ ansible_user }}/.kube/config
        dest: ~/.kube/
        flat: yes
